import os
from multiprocessing import Pool
from process_tools_new import full_process_text
from tqdm import tqdm

if __name__ == '__main__':
    # directory = 'D:\\Work\\projects\\pycharm\\large_txts'
    # file_paths = os.listdir(directory)[1:]
    file_paths = [
        "A_félvérWinnetou_kalandjai.txt",
        "A_föld_alá_vitt_tények_üzenete.txt",
        "A_lóvátett_sárkány.txt",
        "A_lóápoló.txt",
        "A_magyar_sajtó_1944-ben.txt",
        "A_magyar_sajtó_bibliográfiája_1945-1954.txt",
        "A_magyar_sajtó_lelőhelyjegyzéke_1850-1952.txt",
        "Egyetemes_vallástörténet.txt",
        "Egyetlen_érzés_mámorában.txt",
        "Esszék.txt",
        "Kandeláber.txt",
        "Kanitz_Fülöp_Félix_a_Balkán_Kolumbusaélete_és_munkássága.txt",
        "Kanóc_az_emberszelídítő.txt",
        "Kanóc_az_életművész.txt",
        "Mi_pedig_a_Krisztust_prédikáljuk.txt",
        "Mi_szemüvegesek.txt",
        "Mi_székelyek.txt",
        "Mi_volt_előbb_-_Isten_vagy_ősrobbanás.txt",
        "Mire_megvirrad.txt",
        "Mittelalterliche_lateinische_Handschriftenfragmente_in_Győr.txt",
        "Mitől_nem_ér_az_égig.txt",
        "Miért.txt",
        "MiértEgypercesek_novellák.txt",
        "Miért_élvezet_a_szexAz_emberi_szexualitás_evolúciója.txt",
        "Moby_Dick_a_fehér_bálna.txt",
        "Növényi_ornamentika_a_késő_avar_kori_díszítőművészetben(Kr._u._8._század_-_9._század_eleje).txt",
        "Nők_időszaki_kiadványok_és_nyomtatott_nyilvánosság_1820-1920.txt",
        "Nők_és_férfiak_a_hírekben.txt",
        "Nők_és_férfiak_esélyegyenlőségének_elősegítése_a_felnőttképzésben.txt",
        "Nőkről_szerelemről.txt",
        "Nőszerzők_a_19._században.txt",
        "Nősülési_szabályzat_a_magyar_királyi_honvédség_és_a_magyar_királyi_csendőrség_számára.txt",
        "Oceania.txt",
        "Odakint.txt",
        "Odisszea_az_Univerzumban.txt",
        "Odorheiu_Székelyudvarhely_városa.txt",
        "Régi_utak_ködfátyolban.txt",
        "Régi_és_új_peregrináció.txt",
        "Régi_ésvagy_új_reneszánsz.txt",
        "Részletes_dogmatika.txt",
        "Rétegek.txt",
        "Révai_Mór_szakvéleménye_az_árú-részletügyletekről_szóló_törvényjavaslat_tárgyában.txt",
        "Révai_Sámuel_élet-_és_pályarajza.txt",
        "Révhelyi_Elemér_munkássága_a_tatai_múzeum_hagyatéki_gyűjteménye_tükrében.txt",
        "Rózsaláng.txt",
        "Saint_Martin_dans_l'art_en_Europe.txt",
        "Sajtó_a_birodalom_határán.txt",
        "Sajtó_kép_neveléstörténet.txt",
        "Sajtójogi_és_sajtórendészeti_szabályok.txt",
        "Sajtókapcsolatok_kiépítése_és_fönntartása.txt",
        "Sajtószabadságról_nézetei_egy_rabnak.txt",
        "Saját_lábon.txt",
        "Saját_utam_és_erényem_könyve.txt",
        "Sajátos_filozófiám.txt",
        "Sajátos_nevelési_igények_-_méltányos_pedagógia.txt",
        "Sajátos_nevelési_igények_-_méltányos_pedagógia_II..txt",
        "Sajóvölgyi_eredeti_népmesék.txt",
        "Sakk-matt.txt",
        "Salamon_király_kincse.txt",
        "Sanyaró_Vendel_válogatott_nyögései.txt",
        "Sanyi_Manó_könyve_és_számos_más_kacagtató_történet.txt",
        "Sapiens_ubique_civis.txt",
        "Sapienti_sat.txt",
        "Sara_Royce.txt",
        "Sarkövezet.txt",
        "Sarokház.txt",
        "Sasfészkek.txt",
        "Satu.txt",
        "Schlauch_Lőrinc_beszédei_és_dolgozatai.txt",
        "Schrammel.txt",
        "Schrammel_Imre_keramikusművész.txt",
        "Schubert_Ernő_festő_textiltervező.txt",
        "Schéner_MihályTrilógia_1._kötet.txt",
        "Selmec_környékének_geológiai_leírása.txt",
        "Sermones_compilati_in_studio_generali_Quinqueecclesiensi_in_regno_Ungarie.txt",
        "Servadac_Hektor.txt",
        "Seth_könyve.txt",
        "Seth_megszólal.txt",
        "Shajaran.txt",
        "Shakespeare-i_vizeken.txt",
        "Shakespeare-látlatok_I.János_király_Julius_Caesar_Antonius_és_Kleopátra_Athéni_Timon.txt",
        "Shakespeare-látlatok_II..txt",
        "Shakespeare_királynője.txt",
        "Shalom_Barátaim!.txt",
        "Shaping_the_future_through_dialogue_quality_and_education.txt",
        "Sherlock_Holmes_feltámadása_és_egyéb_bünügyi_elbeszélések.txt",
        "Sherlock_Holmes_kalandjai.txt",
        "Shindo_Omaíko_versei.txt",
        "Shiroi_Szenshimate_versei.txt",
        "Shostakovich-syndromeThe_burdened_memories_of_Central_European_societies_in_the_20th_century.txt",
        "Silvia_két_táncosa.txt",
        "Simor_János_római_útinaplója_1874.txt",
        "Siralmas_imádság_és_nemzeti_önszemlélet.txt",
        "Sivatagi_szélben.txt",
        "Sivatagon_és_vadonban.txt",
        "Skandináviai_helyőrség.txt",
        "Smekkerek.txt",
        "Smith_Wigglesworth_titkai.txt",
        "Sms-be_gondolva.txt",
        "Sodrásban_07.txt",
        "Sodrásban_08.txt",
        "Sodrásban_09.txt",
        "Sodrásban_2011.txt",
        "Sodrásban_2012.txt",
        "Sodrásban_2013.txt",
        "Sodrásban_2014.txt",
        "Sodrásban_2015.txt",
        "Sodrásban_2016Kortárs_költők_antológiája_2016.txt",
        "Sodrásban_2017.txt",
        "Sodrásban_2018.txt",
        "Sodrásban_2019.txt",
        "Soha_ne_mondd_hogy_soha.txt",
        "Sok_nagy_malőr.txt",
        "Sokszínű_egészségtudatosság.txt",
        "Sol_mysticus._Az_az_Esterhás_Pál_nagy_sok_virtusokkal_tündöklő_titkos_értelmű_nap_el-nyúgovása_után_.txt",
        "Soli_Deo_Gloria_vezetői_kiskáté.txt",
        "Solo_játékai.txt",
        "System_failureMale_violence_against_women_and_children_as_treated_by_the_legal_system_in_Hungary_tod.txt",
        "Systematisches_Lehrbuch_für_den_Unterricht_im_Säbelfechten_aus_der_Hoch-Tierce-Auslage.txt",
        "Szabad_beszéd.txt",
        "Szabad_vagy.txt",
        "Vallásosság_és_egyházkép_-_interjúk_tükrében.txt",
    ]

    for file in file_paths:
        full_process_text(file)

    # with Pool(processes=4) as pool:
    #     pool.map(full_process_text, file_paths)

# dir = 'D:\\Work\\projects\\pycharm\\txts'
# print(os.listdir(dir))


